nomÂ : DÃ©mo GitHub Actions 
nom d'exÃ©cutionÂ : ${{ github.actor }} teste GitHub Actions ğŸš€ 
surÂ : [push] 
tÃ¢chesÂ : 
  Explore-GitHub-ActionsÂ : 
    s'exÃ©cute surÂ : ubuntu-latest 
    Ã©tapesÂ : 
      - exÃ©cutionÂ : echo "ğŸ‰ La tÃ¢che a Ã©tÃ© dÃ©clenchÃ©e automatiquement par un Ã©vÃ©nement ${{ github.event_name }}." 
      - exÃ©cutionÂ : echo "ğŸ§ Cette tÃ¢che s'exÃ©cute maintenant sur un serveur ${{ runner.os }} hÃ©bergÃ© par GitHubÂ !" 
      - exÃ©cutionÂ : echo "ğŸ” Le nom de votre branche est ${{ github.ref }} et votre dÃ©pÃ´t est ${{ github.repository }}." 
      - nomÂ : Extraire le code du dÃ©pÃ´t 
        utiliseÂ : actions/checkout@v5 
      - exÃ©cutionÂ : echo "ğŸ’¡ Le dÃ©pÃ´t ${{ github.repository }} a Ã©tÃ© clonÃ© sur le runner." 
      - run: echo "ğŸ–¥ï¸ Le workflow est maintenant prÃªt Ã  tester votre code sur le runner." 
      - name: Lister les fichiers du dÃ©pÃ´t 
        run: | 
          ls ${{ github.workspace }} 
      - run: echo "ğŸ Le statut de cette tÃ¢che est ${{ job.status }}."
