name: Main CI/CD ðŸŒŸ

on:
  push:
    branches:
      - main

jobs:
  main-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dÃ©pÃ´t
        uses: actions/checkout@v5

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Installer les dÃ©pendances
        run: |
          pip install -r requirements.txt

      - name: Lancer les tests
        run: |
          echo "âœ… Tests pour la branche main"
          pytest

      - name: DÃ©ploiement (optionnel)
        run: |
          echo "ðŸš€ Ici tu peux mettre ton dÃ©ploiement"
